name: Publish on NPM

on:
    workflow_dispatch:
    push:
        paths:
            - 'package.json'

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node

              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - name: Installing NPM deps
              run: npm install

            - name: Build modules
              run: npm run build

            - name: Publishing on NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
